name: Merge main to develop

on:
  push:
    branches:
      - main

jobs:
  merge-to-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch develop branch
        run: git fetch origin develop

      - name: Checkout develop branch
        run: git checkout develop

      - name: Rebase develop onto main
        run: |
          git checkout develop
          git merge --no-ff main -m "Auto-merge main to develop"
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
