name: Storybook

on:
  pull_request:
    branches:
      - main
      - feature/**
      - develop

  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  deployments: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  storybook-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm --version

      - name: cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-storybook

      - name: dependency install
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: publish to chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyChanged: true
          autoAcceptChanges: true

        env:
          NEXT_PUBLIC_API_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_API_BACKEND_URL }}

      - name: bring current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: "YYYY년 MM월 DD일 HH시 mm분 ss초"
          utcOffset: "+09:00"

    outputs:
      storybook_url: ${{ steps.chromatic.outputs.storybookUrl }}
      currnent_time: ${{ steps.current-time.outputs.formattedTime }}

  github-bot-storybook:
    runs-on: ubuntu-latest
    needs: [storybook-deploy]
    # PR일 때만 실행
    if: github.event_name == 'pull_request'
    steps:
      - name: Leave PR comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: ${{github.event.number}}-storybook
          message: |
            🎨 Storybook: [스토리북 바로가기](${{ needs.storybook-deploy.outputs.storybook_url }})
            ⏰ Update: ${{ needs.storybook-deploy.outputs.currnent_time }}
